### PR TITLE
Make pre-release available

### PR DESCRIPTION
**Pull request by trendelkampschroer**
This pre-release has been around for almost 1yr on pypi and has de-facto become a "stable" dependency of aiohttp.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
Thanks for your contribution! AFAIK pre-releases should be uploaded with a separate label, as commented here: https://github.com/conda-forge/marshmallow-feedstock/issues/40#issue-585214837

and per documentation here:
https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
are you sure about this? The latest stable `aiohttp` release seems to be [3.7.2](https://github.com/aio-libs/aiohttp/releases/tag/v3.7.2) (pretty recent) and it requires [`async-timeout<4.0`](https://github.com/aio-libs/aiohttp/blob/ac294fdded8366b4f8612591bc914e58b4225451/setup.py#L71).

**Comment by ocefpaf** [comment]
Probably covered in #13

**Pull request closed without merging**
